### ISSUE TITLE
Delta scrapper

### ISSUE THREAD

**Issue by martinszy** [seykron/ogov-importer#10]
Here is a page with information on the latest database update:
http://www1.hcdn.gov.ar/proyectos_search/actualizacion.asp?tipo=proyectos

Is this enough to only crawl those documents?

**Comment by seykron** [comment]
Done, now when bills are imported it will generate two output files: the bundle file with all bills, and a delta file with the differences from the previous run. It looks for the previous bundle file in order to enable the history and generate the delta file.
