### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by briatte** [seykron/ogov-importer#19]
As far as I can tell, you have encoding issues in several of the fields. I see an encoding issue in the publishedOn field, with values like `Tr�mite Parlamentario n� 107`, and several `Ñ` characters in the subscribers' names are also garbled. The characters are not garbled in the source:

![screen shot 2015-08-15 at 12 43 30](https://cloud.githubusercontent.com/assets/322533/9288539/4595312e-434b-11e5-9b86-7d783a57b103.png)

**Comment by seykron** [comment]
fixed in branch [refactor-es6](https://github.com/seykron/ogov-importer/tree/feature/refactor-es6)

**Comment by briatte** [comment]
Thanks! Will you update the [ogov-data](https://github.com/seykron/ogov-data) repo accordingly?

**Comment by seykron** [comment]
Yes, but just to let you know, I'm dropping the current directory structure in favour of a single bundle file for each importer, since I'll be implementing a history and opening THAT much files is too expensive. More details [in this discussion](https://github.com/seykron/ogov-importer/issues/7#issuecomment-148915268).

**Comment by briatte** [comment]
Not a problem for me, I never really understood the directory structure in the first place!

A related question is: will the encoding fix also apply to the political parties of the bill sponsors? There are hundreds of different party names, and some of them have special characters.

Also, if you know any means to reduce the overall number of parties, I'm very interested. I've tried merging your data and that of [Ernesto Calvo](http://gvptsites.umd.edu/calvo/cosponsorship.htm), in order to find the larger 'bloc' to which each party belongs, but his data are more limited than yours, and the merge still leaves dozens of parties with no bloc.
